=== IleniaCentonze/terminology/input/vocabulary/esenzioni/Tipologia.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Tipologia" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Tipologia">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="code " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="GUID" type="9" value="oDo216pUykG72NwvzPWavg==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAACgOjbXqlTKQbvY3C/M9Zq+AAAAACEaBDizeOVAAAAAAAAAAABUAGkA
cABvAGwAbwBnAGkAYQAAAAAAAABKvwaHM4SlQK5E4F/TfMQBBwAAAKA6NteqVMpB
u9jcL8z1mr5jAG8AZABlAAAAAAAAAJxpAUHSTNdJpbQ/8Tb9yVYHAAAAoDo216pU
ykG72NwvzPWavmQAaQBzAHAAbABhAHkAAAAAAAAAeh9M7W6nl02yQika0A/p8QcA
AACgOjbXqlTKQbvY3C/M9Zq+bgBvAHQAUwBlAGwAZQBjAHQAYQBiAGwAZQAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAADAAAAAUAAAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="code" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="Sr8GhzOEpUCuROBf03zEAQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="display" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="nGkBQdJM10mltD/xNv3JVg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2905"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="notSelectable" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="eh9M7W6nl02yQika0A/p8Q==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="No"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== IleniaCentonze/terminology/input/vocabulary/esenzioni/Tipologia.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Tipologia.xsd" generated="2020-05-22T14:27:45">
<Tipologia>
<code>F0</code>
<display>DETENUTI</display>
<notSelectable>1</notSelectable>
</Tipologia>
<Tipologia>
<code>D0</code>
<display>DIAGNOSI PRECOCE</display>
<notSelectable>1</notSelectable>
</Tipologia>
<Tipologia>
<code>T0</code>
<display>DONAZIONE</display>
<notSelectable>1</notSelectable>
</Tipologia>
<Tipologia>
<code>X0</code>
<display>EXTRACOMUNITARI</display>
<notSelectable>1</notSelectable>
</Tipologia>
<Tipologia>
<code>B0</code>
<display>HIV</display>
<notSelectable>1</notSelectable>
</Tipologia>
<Tipologia>
<code>I0</code>
<display>IDONEITA&apos;</display>
<notSelectable>1</notSelectable>
</Tipologia>
<Tipologia>
<code>INVC</code>
<display>INVALIDI CIVILI</display>
<notSelectable>1</notSelectable>
</Tipologia>
<Tipologia>
<code>INVL</code>
<display>INVALIDI DEL LAVORO</display>
<notSelectable>1</notSelectable>
</Tipologia>
<Tipologia>
<code>INVG</code>
<display>INVALIDI DI GUERRA</display>
<notSelectable>1</notSelectable>
</Tipologia>
<Tipologia>
<code>N0</code>
<display>LEGGE N. 210</display>
<notSelectable>1</notSelectable>
</Tipologia>
<Tipologia>
<code>MC</code>
<display>MALATTIE CRONICHE</display>
<notSelectable>1</notSelectable>
</Tipologia>
<Tipologia>
<code>RX</code>
<display>MALATTIE RARA</display>
<notSelectable>1</notSelectable>
</Tipologia>
<Tipologia>
<code>M</code>
<display>MATERNITA</display>
<notSelectable>0</notSelectable>
</Tipologia>
<Tipologia>
<code>PM</code>
<display>PRESTAZIONI MEDICO LEGALI</display>
<notSelectable>1</notSelectable>
</Tipologia>
<Tipologia>
<code>P0</code>
<display>PREVENZIONE</display>
<notSelectable>1</notSelectable>
</Tipologia>
<Tipologia>
<code>RD</code>
<display>REDDITO</display>
<notSelectable>1</notSelectable>
</Tipologia>
<Tipologia>
<code>S0</code>
<display>SERVIZIO</display>
<notSelectable>1</notSelectable>
</Tipologia>
<Tipologia>
<code>TD</code>
<display>TERAPIA DEL DOLORE SEVERO</display>
<notSelectable>1</notSelectable>
</Tipologia>
<Tipologia>
<code>V0</code>
<display>VITTIME DEL TERRORISMO</display>
<notSelectable>1</notSelectable>
</Tipologia>
</dataroot>
