=== IleniaCentonze/terminology/input/vocabulary/unitaTeritoriali/Provincie.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Provincie" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Provincie">
<xsd:annotation>
<xsd:appinfo/>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="code" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="display" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="codice_x0020_provincia" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="targa" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Codice_x0020_Regione" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Tipologia_x0020_unitÃ _x0020_territoriale_x0020_sovracomunale" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="COD_UTS_AM" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="NUTS3" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Note" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== IleniaCentonze/terminology/input/vocabulary/unitaTeritoriali/Provincie.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Provincie.xsd" generated="2020-03-06T08:47:22">
<Provincie>
<code>002</code>
<display>Vercelli</display>
<codice_x0020_provincia>002</codice_x0020_provincia>
<targa>VC</targa>
<Codice_x0020_Regione>01</Codice_x0020_Regione>
<Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>Provincia</Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>
<COD_UTS_AM>002</COD_UTS_AM>
<NUTS3>ITC12</NUTS3>
</Provincie>
<Provincie>
<code>003</code>
<display>Novara</display>
<codice_x0020_provincia>003</codice_x0020_provincia>
<targa>NO</targa>
<Codice_x0020_Regione>01</Codice_x0020_Regione>
<Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>Provincia</Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>
<COD_UTS_AM>003</COD_UTS_AM>
<NUTS3>ITC15</NUTS3>
</Provincie>
<Provincie>
<code>004</code>
<display>Cuneo</display>
<codice_x0020_provincia>004</codice_x0020_provincia>
<targa>CN</targa>
<Codice_x0020_Regione>01</Codice_x0020_Regione>
<Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>Provincia</Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>
<COD_UTS_AM>004</COD_UTS_AM>
<NUTS3>ITC16</NUTS3>
</Provincie>
<Provincie>
<code>005</code>
<display>Asti</display>
<codice_x0020_provincia>005</codice_x0020_provincia>
<targa>AT</targa>
<Codice_x0020_Regione>01</Codice_x0020_Regione>
<Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>Provincia</Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>
<COD_UTS_AM>005</COD_UTS_AM>
<NUTS3>ITC17</NUTS3>
</Provincie>
<Provincie>
<code>006</code>
<display>Alessandria</display>
<codice_x0020_provincia>006</codice_x0020_provincia>
<targa>AL</targa>
<Codice_x0020_Regione>01</Codice_x0020_Regione>
<Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>Provincia</Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>
<COD_UTS_AM>006</COD_UTS_AM>
<NUTS3>ITC18</NUTS3>
</Provincie>
<Provincie>
<code>007</code>
<display>Valle d&apos;Aosta/Vallée d&apos;Aoste</display>
<codice_x0020_provincia>007</codice_x0020_provincia>
<targa>AO</targa>
<Codice_x0020_Regione>02</Codice_x0020_Regione>
<Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>Provincia</Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>
<COD_UTS_AM>007</COD_UTS_AM>
<NUTS3>ITC20</NUTS3>
</Provincie>
<Provincie>
<code>008</code>
<display>Imperia</display>
<codice_x0020_provincia>008</codice_x0020_provincia>
<targa>IM</targa>
<Codice_x0020_Regione>07</Codice_x0020_Regione>
<Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>Provincia</Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>
<COD_UTS_AM>008</COD_UTS_AM>
<NUTS3>ITC31</NUTS3>
</Provincie>
<Provincie>
<code>009</code>
<display>Savona</display>
<codice_x0020_provincia>009</codice_x0020_provincia>
<targa>SV</targa>
<Codice_x0020_Regione>07</Codice_x0020_Regione>
<Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>Provincia</Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>
<COD_UTS_AM>009</COD_UTS_AM>
<NUTS3>ITC32</NUTS3>
</Provincie>
<Provincie>
<code>011</code>
<display>La Spezia</display>
<codice_x0020_provincia>011</codice_x0020_provincia>
<targa>SP</targa>
<Codice_x0020_Regione>07</Codice_x0020_Regione>
<Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>Provincia</Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>
<COD_UTS_AM>011</COD_UTS_AM>
<NUTS3>ITC34</NUTS3>
</Provincie>
<Provincie>
<code>012</code>
<display>Varese</display>
<codice_x0020_provincia>012</codice_x0020_provincia>
<targa>VA</targa>
<Codice_x0020_Regione>03</Codice_x0020_Regione>
<Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>Provincia</Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>
<COD_UTS_AM>012</COD_UTS_AM>
<NUTS3>ITC41</NUTS3>
</Provincie>
<Provincie>
<code>013</code>
<display>Como</display>
<codice_x0020_provincia>013</codice_x0020_provincia>
<targa>CO</targa>
<Codice_x0020_Regione>03</Codice_x0020_Regione>
<Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>Provincia</Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>
<COD_UTS_AM>013</COD_UTS_AM>
<NUTS3>ITC42</NUTS3>
</Provincie>
<Provincie>
<code>014</code>
<display>Sondrio</display>
<codice_x0020_provincia>014</codice_x0020_provincia>
<targa>SO</targa>
<Codice_x0020_Regione>03</Codice_x0020_Regione>
<Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>Provincia</Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>
<COD_UTS_AM>014</COD_UTS_AM>
<NUTS3>ITC44</NUTS3>
</Provincie>
<Provincie>
<code>016</code>
<display>Bergamo</display>
<codice_x0020_provincia>016</codice_x0020_provincia>
<targa>BG</targa>
<Codice_x0020_Regione>03</Codice_x0020_Regione>
<Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>Provincia</Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>
<COD_UTS_AM>016</COD_UTS_AM>
<NUTS3>ITC46</NUTS3>
</Provincie>
<Provincie>
<code>017</code>
<display>Brescia</display>
<codice_x0020_provincia>017</codice_x0020_provincia>
<targa>BS</targa>
<Codice_x0020_Regione>03</Codice_x0020_Regione>
<Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>Provincia</Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>
<COD_UTS_AM>017</COD_UTS_AM>
<NUTS3>ITC47</NUTS3>
</Provincie>
<Provincie>
<code>018</code>
<display>Pavia</display>
<codice_x0020_provincia>018</codice_x0020_provincia>
<targa>PV</targa>
<Codice_x0020_Regione>03</Codice_x0020_Regione>
<Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>Provincia</Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>
<COD_UTS_AM>018</COD_UTS_AM>
<NUTS3>ITC48</NUTS3>
</Provincie>
<Provincie>
<code>019</code>
<display>Cremona</display>
<codice_x0020_provincia>019</codice_x0020_provincia>
<targa>CR</targa>
<Codice_x0020_Regione>03</Codice_x0020_Regione>
<Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>Provincia</Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>
<COD_UTS_AM>019</COD_UTS_AM>
<NUTS3>ITC4A</NUTS3>
</Provincie>
<Provincie>
<code>020</code>
<display>Mantova</display>
<codice_x0020_provincia>020</codice_x0020_provincia>
<targa>MN</targa>
<Codice_x0020_Regione>03</Codice_x0020_Regione>
<Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>Provincia</Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>
<COD_UTS_AM>020</COD_UTS_AM>
<NUTS3>ITC4B</NUTS3>
</Provincie>
<Provincie>
<code>021</code>
<display>Bolzano/Bozen</display>
<codice_x0020_provincia>021</codice_x0020_provincia>
<targa>BZ</targa>
<Codice_x0020_Regione>04</Codice_x0020_Regione>
<Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>Provincia autonoma</Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>
<COD_UTS_AM>021</COD_UTS_AM>
<NUTS3>ITH10</NUTS3>
</Provincie>
<Provincie>
<code>022</code>
<display>Trento</display>
<codice_x0020_provincia>022</codice_x0020_provincia>
<targa>TN</targa>
<Codice_x0020_Regione>04</Codice_x0020_Regione>
<Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>Provincia autonoma</Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>
<COD_UTS_AM>022</COD_UTS_AM>
<NUTS3>ITH20</NUTS3>
</Provincie>
<Provincie>
<code>023</code>
<display>Verona</display>
<codice_x0020_provincia>023</codice_x0020_provincia>
<targa>VR</targa>
<Codice_x0020_Regione>05</Codice_x0020_Regione>
<Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>Provincia</Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>
<COD_UTS_AM>023</COD_UTS_AM>
<NUTS3>ITH31</NUTS3>
</Provincie>
<Provincie>
<code>024</code>
<display>Vicenza</display>
<codice_x0020_provincia>024</codice_x0020_provincia>
<targa>VI</targa>
<Codice_x0020_Regione>05</Codice_x0020_Regione>
<Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>Provincia</Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>
<COD_UTS_AM>024</COD_UTS_AM>
<NUTS3>ITH32</NUTS3>
</Provincie>
<Provincie>
<code>025</code>
<display>Belluno</display>
<codice_x0020_provincia>025</codice_x0020_provincia>
<targa>BL</targa>
<Codice_x0020_Regione>05</Codice_x0020_Regione>
<Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>Provincia</Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>
<COD_UTS_AM>025</COD_UTS_AM>
<NUTS3>ITH33</NUTS3>
</Provincie>
<Provincie>
<code>026</code>
<display>Treviso</display>
<codice_x0020_provincia>026</codice_x0020_provincia>
<targa>TV</targa>
<Codice_x0020_Regione>05</Codice_x0020_Regione>
<Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>Provincia</Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>
<COD_UTS_AM>026</COD_UTS_AM>
<NUTS3>ITH34</NUTS3>
</Provincie>
<Provincie>
<code>028</code>
<display>Padova</display>
<codice_x0020_provincia>028</codice_x0020_provincia>
<targa>PD</targa>
<Codice_x0020_Regione>05</Codice_x0020_Regione>
<Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>Provincia</Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>
<COD_UTS_AM>028</COD_UTS_AM>
<NUTS3>ITH36</NUTS3>
</Provincie>
<Provincie>
<code>029</code>
<display>Rovigo</display>
<codice_x0020_provincia>029</codice_x0020_provincia>
<targa>RO</targa>
<Codice_x0020_Regione>05</Codice_x0020_Regione>
<Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>Provincia</Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>
<COD_UTS_AM>029</COD_UTS_AM>
<NUTS3>ITH37</NUTS3>
</Provincie>
<Provincie>
<code>030</code>
<display>Udine</display>
<codice_x0020_provincia>030</codice_x0020_provincia>
<targa>UD</targa>
<Codice_x0020_Regione>06</Codice_x0020_Regione>
<Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>Unità non amministrativa</Tipologia_x0020_unità_x0020_territoriale_x0020_sovracomunale>
<COD_UTS_AM>-</COD_UTS_AM>
<NUTS3>ITH42</NUTS3>
<Note>(f)</Note>
