=== IleniaCentonze/terminology/input/vocabulary/fls11/ASL_distinct.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="ASL_distinct" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="ASL_distinct">
<xsd:annotation>
<xsd:appinfo>
<od:tableProperty name="GUID" type="9" value="6NW5swwgsk6m1PIoNUomSg==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="1"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAADo1bmzDCCyTqbU8ig1SiZKAAAAAB3YtX6aeuVAAAAAAAAAAABBAFMA
TABfAGQAaQBzAHQAaQBuAGMAdAAAAAAAAABS+R0VPqFaSoogpazmXFEyBwAAAOjV
ubMMILJOptTyKDVKJkpJAE4ARABJAFIASQBaAFoATwAAAAAAAADh2RE/uVnwT5mf
ZxLQmehkBwAAAOjVubMMILJOptTyKDVKJkpDAE8ATQBVAE4ARQAAAAAAAADvm/FE
esHNTbsNj7vF7D+5BwAAAOjVubMMILJOptTyKDVKJkpjAG8AZABlAAAAAAAAAEvt
QxWICV1DtIAMvvNjvvUHAAAA6NW5swwgsk6m1PIoNUomSkEATgBOAE8AAAAAAAAA
VZjxDD+OE0G2oZgvMEmLpwcAAADo1bmzDCCyTqbU8ig1SiZKQwBPAEQASQBDAEUA
IABSAEUARwBJAE8ATgBFAAAAAAAAAAvcen88DgVNoQ6djlgT+0oHAAAA6NW5swwg
sk6m1PIoNUomSkQARQBOAE8ATQBJAE4AQQBaAEkATwBOAEUAIABSAEUARwBJAE8A
TgBFAAAAAAAAADGzw0DxAL5CpVXLedHLFZ0HAAAA6NW5swwgsk6m1PIoNUomSkMA
TwBEAEkAQwBFACAAQQBaAEkARQBOAEQAQQAAAAAAAAB/vyuHs8CfT5e4/gAueaXL
BwAAAOjVubMMILJOptTyKDVKJkpEAEUATgBPAE0ASQBOAEEAWgBJAE8ATgBFACAA
QQBaAEkARQBOAEQAQQAAAAAAAADnsdB9LzzOQrUVmmtKm/EWBwAAAOjVubMMILJO
ptTyKDVKJkpDAEEAUAAAAAAAAABRTw/eNEkOQrTdQbXfEfvMBwAAAOjVubMMILJO
ptTyKDVKJkpTAEkARwBMAEEAIABQAFIATwBWAEkATgBDAEkAQQAAAAAAAAB7GFJT
yl2uS5gw/NlRvJ7UBwAAAOjVubMMILJOptTyKDVKJkpzAHQAYQB0AG8AAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAwAAAAFAAAAAAAAAAAAAAAAAAAAAAA=
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="100"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="OrderBy" type="12" value="[ASL_distinct].[code]"/>
<od:tableProperty name="Filter" type="12" value="(((ASL_distinct.INDIRIZZO Like &quot;*&quot;))) And (ASL_distinct.COMUNE Like &quot;loc*&quot;)"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="code" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="75vxRHrBzU27DY+7xew/uQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1105"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="ANNO" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="S+1DFYgJXUO0gAy+82O+9Q==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="CODICE_x0020_REGIONE" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="VZjxDD+OE0G2oZgvMEmLpw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="DENOMINAZIONE_x0020_REGIONE" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="C9x6fzwOBU2hDp2OWBP7Sg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="CODICE_x0020_AZIENDA" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="MbPDQPEAvkKlVct50csVnQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="DENOMINAZIONE_x0020_AZIENDA" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="f78rh7PAn0+XuP4ALnmlyw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="4135"/>
<od:fieldProperty name="ColumnOrder" type="3" value="6"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="INDIRIZZO" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="UvkdFT6hWkqKIKWs5lxRMg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="3785"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="CAP" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="57HQfS88zkK1FZprSpvxFg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="COMUNE" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="4dkRP7lZ8E+Zn2cS0JnoZA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="SIGLA_x0020_PROVINCIA" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="UU8P3jRJDkK03UG13xH7zA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="stato" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="exhSU8pdrkuYMPzZUbye1A==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== IleniaCentonze/terminology/input/vocabulary/fls11/ASL_distinct.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="ASL_distinct.xsd" generated="2020-06-07T00:08:20">
<ASL_distinct>
<code>150206</code>
<ANNO>2020</ANNO>
<CODICE_x0020_REGIONE>150</CODICE_x0020_REGIONE>
<DENOMINAZIONE_x0020_REGIONE>CAMPANIA</DENOMINAZIONE_x0020_REGIONE>
<CODICE_x0020_AZIENDA>206</CODICE_x0020_AZIENDA>
<DENOMINAZIONE_x0020_AZIENDA>A.S.L. NAPOLI 3 SUD</DENOMINAZIONE_x0020_AZIENDA>
<INDIRIZZO>C.SO ALCIDE DE GASPERI 167</INDIRIZZO>
<CAP>80053</CAP>
<COMUNE>CASTELLAMMARE DI STABIA</COMUNE>
<SIGLA_x0020_PROVINCIA>NA</SIGLA_x0020_PROVINCIA>
<stato>active</stato>
</ASL_distinct>
<ASL_distinct>
<code>180203</code>
<ANNO>2020</ANNO>
<CODICE_x0020_REGIONE>180</CODICE_x0020_REGIONE>
<DENOMINAZIONE_x0020_REGIONE>CALABRIA</DENOMINAZIONE_x0020_REGIONE>
<CODICE_x0020_AZIENDA>203</CODICE_x0020_AZIENDA>
<DENOMINAZIONE_x0020_AZIENDA>A.S.P. CATANZARO</DENOMINAZIONE_x0020_AZIENDA>
<INDIRIZZO>VIA VINICIO CORTESE 25</INDIRIZZO>
<CAP>88100</CAP>
<COMUNE>CATANZARO</COMUNE>
<SIGLA_x0020_PROVINCIA>CZ</SIGLA_x0020_PROVINCIA>
<stato>active</stato>
</ASL_distinct>
<ASL_distinct>
<code>150205</code>
<ANNO>2020</ANNO>
<CODICE_x0020_REGIONE>150</CODICE_x0020_REGIONE>
<DENOMINAZIONE_x0020_REGIONE>CAMPANIA</DENOMINAZIONE_x0020_REGIONE>
<CODICE_x0020_AZIENDA>205</CODICE_x0020_AZIENDA>
<DENOMINAZIONE_x0020_AZIENDA>A.S.L. NAPOLI 2 NORD</DENOMINAZIONE_x0020_AZIENDA>
<INDIRIZZO>VIA CORRADO ALVARO 8</INDIRIZZO>
<CAP>80078</CAP>
<COMUNE>POZZUOLI</COMUNE>
<SIGLA_x0020_PROVINCIA>NA</SIGLA_x0020_PROVINCIA>
<stato>active</stato>
</ASL_distinct>
<ASL_distinct>
<code>180205</code>
<ANNO>2020</ANNO>
<CODICE_x0020_REGIONE>180</CODICE_x0020_REGIONE>
<DENOMINAZIONE_x0020_REGIONE>CALABRIA</DENOMINAZIONE_x0020_REGIONE>
<CODICE_x0020_AZIENDA>205</CODICE_x0020_AZIENDA>
<DENOMINAZIONE_x0020_AZIENDA>A.S.P. REGGIO CALABRIA</DENOMINAZIONE_x0020_AZIENDA>
<INDIRIZZO>VIA SANT&apos;ANNA II TRONCO 18/P</INDIRIZZO>
<CAP>89128</CAP>
<COMUNE>REGGIO DI CALABRIA</COMUNE>
<SIGLA_x0020_PROVINCIA>RC</SIGLA_x0020_PROVINCIA>
<stato>active</stato>
</ASL_distinct>
<ASL_distinct>
<code>190201</code>
<ANNO>2020</ANNO>
<CODICE_x0020_REGIONE>190</CODICE_x0020_REGIONE>
<DENOMINAZIONE_x0020_REGIONE>SICILIA</DENOMINAZIONE_x0020_REGIONE>
<CODICE_x0020_AZIENDA>201</CODICE_x0020_AZIENDA>
<DENOMINAZIONE_x0020_AZIENDA>ASP AGRIGENTO</DENOMINAZIONE_x0020_AZIENDA>
<INDIRIZZO>VIA MANZONI  140</INDIRIZZO>
<CAP>92100</CAP>
<COMUNE>AGRIGENTO</COMUNE>
<SIGLA_x0020_PROVINCIA>AG</SIGLA_x0020_PROVINCIA>
<stato>active</stato>
</ASL_distinct>
<ASL_distinct>
<code>190202</code>
<ANNO>2020</ANNO>
<CODICE_x0020_REGIONE>190</CODICE_x0020_REGIONE>
<DENOMINAZIONE_x0020_REGIONE>SICILIA</DENOMINAZIONE_x0020_REGIONE>
<CODICE_x0020_AZIENDA>202</CODICE_x0020_AZIENDA>
<DENOMINAZIONE_x0020_AZIENDA>ASP CALTANISSETTA</DENOMINAZIONE_x0020_AZIENDA>
<INDIRIZZO>VIA CUSMANO 10</INDIRIZZO>
<CAP>93100</CAP>
<COMUNE>CALTANISSETTA</COMUNE>
<SIGLA_x0020_PROVINCIA>CL</SIGLA_x0020_PROVINCIA>
<stato>active</stato>
</ASL_distinct>
<ASL_distinct>
<code>190203</code>
<ANNO>2020</ANNO>
<CODICE_x0020_REGIONE>190</CODICE_x0020_REGIONE>
<DENOMINAZIONE_x0020_REGIONE>SICILIA</DENOMINAZIONE_x0020_REGIONE>
<CODICE_x0020_AZIENDA>203</CODICE_x0020_AZIENDA>
<DENOMINAZIONE_x0020_AZIENDA>ASP CATANIA</DENOMINAZIONE_x0020_AZIENDA>
<INDIRIZZO>VIA S. MARIA LA GRANDE 5</INDIRIZZO>
<CAP>95124</CAP>
<COMUNE>CATANIA</COMUNE>
<SIGLA_x0020_PROVINCIA>CT</SIGLA_x0020_PROVINCIA>
<stato>active</stato>
</ASL_distinct>
<ASL_distinct>
<code>190204</code>
<ANNO>2020</ANNO>
<CODICE_x0020_REGIONE>190</CODICE_x0020_REGIONE>
<DENOMINAZIONE_x0020_REGIONE>SICILIA</DENOMINAZIONE_x0020_REGIONE>
<CODICE_x0020_AZIENDA>204</CODICE_x0020_AZIENDA>
<DENOMINAZIONE_x0020_AZIENDA>ASP ENNA</DENOMINAZIONE_x0020_AZIENDA>
<INDIRIZZO>VIALE DIAZ 23</INDIRIZZO>
<CAP>94100</CAP>
<COMUNE>ENNA</COMUNE>
<SIGLA_x0020_PROVINCIA>EN</SIGLA_x0020_PROVINCIA>
<stato>active</stato>
</ASL_distinct>
<ASL_distinct>
<code>190205</code>
<ANNO>2020</ANNO>
<CODICE_x0020_REGIONE>190</CODICE_x0020_REGIONE>
<DENOMINAZIONE_x0020_REGIONE>SICILIA</DENOMINAZIONE_x0020_REGIONE>
<CODICE_x0020_AZIENDA>205</CODICE_x0020_AZIENDA>
<DENOMINAZIONE_x0020_AZIENDA>ASP MESSINA</DENOMINAZIONE_x0020_AZIENDA>
<INDIRIZZO>VIA DEL VESPRO  289</INDIRIZZO>
<CAP>98100</CAP>
<COMUNE>MESSINA</COMUNE>
<SIGLA_x0020_PROVINCIA>ME</SIGLA_x0020_PROVINCIA>
<stato>active</stato>
</ASL_distinct>
<ASL_distinct>
<code>190206</code>
<ANNO>2020</ANNO>
<CODICE_x0020_REGIONE>190</CODICE_x0020_REGIONE>
<DENOMINAZIONE_x0020_REGIONE>SICILIA</DENOMINAZIONE_x0020_REGIONE>
<CODICE_x0020_AZIENDA>206</CODICE_x0020_AZIENDA>
<DENOMINAZIONE_x0020_AZIENDA>ASP PALERMO</DENOMINAZIONE_x0020_AZIENDA>
<INDIRIZZO>VIA G. CUSMANO 24</INDIRIZZO>
<CAP>90100</CAP>
<COMUNE>PALERMO</COMUNE>
<SIGLA_x0020_PROVINCIA>PA</SIGLA_x0020_PROVINCIA>
<stato>active</stato>
</ASL_distinct>
<ASL_distinct>
<code>190207</code>
<ANNO>2020</ANNO>
<CODICE_x0020_REGIONE>190</CODICE_x0020_REGIONE>
<DENOMINAZIONE_x0020_REGIONE>SICILIA</DENOMINAZIONE_x0020_REGIONE>
<CODICE_x0020_AZIENDA>207</CODICE_x0020_AZIENDA>
<DENOMINAZIONE_x0020_AZIENDA>ASP RAGUSA</DENOMINAZIONE_x0020_AZIENDA>
<INDIRIZZO>P.ZZA IGEA 1</INDIRIZZO>
<CAP>97100</CAP>
<COMUNE>RAGUSA</COMUNE>
<SIGLA_x0020_PROVINCIA>RG</SIGLA_x0020_PROVINCIA>
<stato>active</stato>
</ASL_distinct>
<ASL_distinct>
<code>190208</code>
<ANNO>2020</ANNO>
<CODICE_x0020_REGIONE>190</CODICE_x0020_REGIONE>
<DENOMINAZIONE_x0020_REGIONE>SICILIA</DENOMINAZIONE_x0020_REGIONE>
<CODICE_x0020_AZIENDA>208</CODICE_x0020_AZIENDA>
<DENOMINAZIONE_x0020_AZIENDA>ASP SIRACUSA</DENOMINAZIONE_x0020_AZIENDA>
<INDIRIZZO>C.SO GELONE 17</INDIRIZZO>
<CAP>96100</CAP>
<COMUNE>SIRACUSA</COMUNE>
<SIGLA_x0020_PROVINCIA>SR</SIGLA_x0020_PROVINCIA>
<stato>active</stato>
</ASL_distinct>
<ASL_distinct>
<code>190209</code>
<ANNO>2020</ANNO>
<CODICE_x0020_REGIONE>190</CODICE_x0020_REGIONE>
<DENOMINAZIONE_x0020_REGIONE>SICILIA</DENOMINAZIONE_x0020_REGIONE>
<CODICE_x0020_AZIENDA>209</CODICE_x0020_AZIENDA>
<DENOMINAZIONE_x0020_AZIENDA>ASP DI TRAPANI</DENOMINAZIONE_x0020_AZIENDA>
<INDIRIZZO>VIA MAZZINI 1</INDIRIZZO>
<CAP>91100</CAP>
<COMUNE>TRAPANI</COMUNE>
<SIGLA_x0020_PROVINCIA>TP</SIGLA_x0020_PROVINCIA>
<stato>active</stato>
</ASL_distinct>
<ASL_distinct>
<code>180202</code>
<ANNO>2020</ANNO>
<CODICE_x0020_REGIONE>180</CODICE_x0020_REGIONE>
<DENOMINAZIONE_x0020_REGIONE>CALABRIA</DENOMINAZIONE_x0020_REGIONE>
<CODICE_x0020_AZIENDA>202</CODICE_x0020_AZIENDA>
<DENOMINAZIONE_x0020_AZIENDA>A.S.P. CROTONE</DENOMINAZIONE_x0020_AZIENDA>
<INDIRIZZO>VIA CORIGLIANO 1</INDIRIZZO>
<CAP>88900</CAP>
<COMUNE>CROTONE</COMUNE>
<SIGLA_x0020_PROVINCIA>KR</SIGLA_x0020_PROVINCIA>
<stato>active</stato>
</ASL_distinct>
<ASL_distinct>
<code>120205</code>
<ANNO>2020</ANNO>
<CODICE_x0020_REGIONE>120</CODICE_x0020_REGIONE>
<DENOMINAZIONE_x0020_REGIONE>LAZIO</DENOMINAZIONE_x0020_REGIONE>
<CODICE_x0020_AZIENDA>205</CODICE_x0020_AZIENDA>
<DENOMINAZIONE_x0020_AZIENDA>ROMA 5</DENOMINAZIONE_x0020_AZIENDA>
<INDIRIZZO>VIA TIBURTINA 22/A</INDIRIZZO>
<CAP>00019</CAP>
<COMUNE>TIVOLI</COMUNE>
<SIGLA_x0020_PROVINCIA>RM</SIGLA_x0020_PROVINCIA>
<stato>active</stato>
</ASL_distinct>
<ASL_distinct>
<code>200201</code>
<ANNO>2020</ANNO>
<CODICE_x0020_REGIONE>200</CODICE_x0020_REGIONE>
<DENOMINAZIONE_x0020_REGIONE>SARDEGNA</DENOMINAZIONE_x0020_REGIONE>
<CODICE_x0020_AZIENDA>201</CODICE_x0020_AZIENDA>
<DENOMINAZIONE_x0020_AZIENDA>AZIENDA PER LA TUTELA DELLA SALUTE</DENOMINAZIONE_x0020_AZIENDA>
<INDIRIZZO>VIA MONTE GRAPPA 82</INDIRIZZO>
<CAP>07100</CAP>
<COMUNE>SASSARI</COMUNE>
<SIGLA_x0020_PROVINCIA>SS</SIGLA_x0020_PROVINCIA>
<stato>active</stato>
</ASL_distinct>
<ASL_distinct>
<code>100201</code>
<ANNO>2020</ANNO>
<CODICE_x0020_REGIONE>100</CODICE_x0020_REGIONE>
<DENOMINAZIONE_x0020_REGIONE>UMBRIA</DENOMINAZIONE_x0020_REGIONE>
<CODICE_x0020_AZIENDA>201</CODICE_x0020_AZIENDA>
<DENOMINAZIONE_x0020_AZIENDA>AUSL UMBRIA N. 1</DENOMINAZIONE_x0020_AZIENDA>
<INDIRIZZO>VIA G. GUERRA  21/17</INDIRIZZO>
<CAP>06127</CAP>
<COMUNE>PERUGIA</COMUNE>
<SIGLA_x0020_PROVINCIA>PG</SIGLA_x0020_PROVINCIA>
<stato>active</stato>
</ASL_distinct>
<ASL_distinct>
<code>100202</code>
<ANNO>2020</ANNO>
<CODICE_x0020_REGIONE>100</CODICE_x0020_REGIONE>
<DENOMINAZIONE_x0020_REGIONE>UMBRIA</DENOMINAZIONE_x0020_REGIONE>
<CODICE_x0020_AZIENDA>202</CODICE_x0020_AZIENDA>
<DENOMINAZIONE_x0020_AZIENDA>AUSL UMBRIA N. 2</DENOMINAZIONE_x0020_AZIENDA>
<INDIRIZZO>VIALE BRAMANTE  37</INDIRIZZO>
<CAP>05100</CAP>
<COMUNE>TERNI</COMUNE>
<SIGLA_x0020_PROVINCIA>TR</SIGLA_x0020_PROVINCIA>
<stato>active</stato>
</ASL_distinct>
<ASL_distinct>
<code>110201</code>
<ANNO>2020</ANNO>
<CODICE_x0020_REGIONE>110</CODICE_x0020_REGIONE>
<DENOMINAZIONE_x0020_REGIONE>MARCHE</DENOMINAZIONE_x0020_REGIONE>
<CODICE_x0020_AZIENDA>201</CODICE_x0020_AZIENDA>
<DENOMINAZIONE_x0020_AZIENDA>ASUR</DENOMINAZIONE_x0020_AZIENDA>
<INDIRIZZO>Via G. Oberdan 2</INDIRIZZO>
<CAP>60122</CAP>
<COMUNE>ANCONA</COMUNE>
<SIGLA_x0020_PROVINCIA>AN</SIGLA_x0020_PROVINCIA>
<stato>active</stato>
</ASL_distinct>
<ASL_distinct>
<code>120109</code>
<ANNO>2020</ANNO>
<CODICE_x0020_REGIONE>120</CODICE_x0020_REGIONE>
<DENOMINAZIONE_x0020_REGIONE>LAZIO</DENOMINAZIONE_x0020_REGIONE>
<CODICE_x0020_AZIENDA>109</CODICE_x0020_AZIENDA>
<DENOMINAZIONE_x0020_AZIENDA>VITERBO</DENOMINAZIONE_x0020_AZIENDA>
<INDIRIZZO>VIA ENRICO FERMI 15</INDIRIZZO>
<CAP>01100</CAP>
<COMUNE>VITERBO</COMUNE>
<SIGLA_x0020_PROVINCIA>VT</SIGLA_x0020_PROVINCIA>
<stato>active</stato>
</ASL_distinct>
<ASL_distinct>
<code>120110</code>
<ANNO>2020</ANNO>
<CODICE_x0020_REGIONE>120</CODICE_x0020_REGIONE>
<DENOMINAZIONE_x0020_REGIONE>LAZIO</DENOMINAZIONE_x0020_REGIONE>
<CODICE_x0020_AZIENDA>110</CODICE_x0020_AZIENDA>
<DENOMINAZIONE_x0020_AZIENDA>RIETI</DENOMINAZIONE_x0020_AZIENDA>
<INDIRIZZO>VIALE  MATTEUCCI 9</INDIRIZZO>
<CAP>02100</CAP>
<COMUNE>RIETI</COMUNE>
<SIGLA_x0020_PROVINCIA>RI</SIGLA_x0020_PROVINCIA>
<stato>active</stato>
