=== IleniaCentonze/terminology/input/vocabulary/statiEsteri/Territori_Figli.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Territori_Figli" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Territori_Figli">
<xsd:annotation>
<xsd:appinfo/>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="Stato_x0028_S_x0029__x002F_Territorio_x0028_T_x0029_" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Codice_x0020_Continente" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double"/>
<xsd:element name="Denominazione_x0020_Continente_x0020__x0028_IT_x0029_" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Codice_x0020_Area" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double"/>
<xsd:element name="Denominazione_x0020_Area_x0020__x0028_IT_x0029_" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="code" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double"/>
<xsd:element name="display" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Denominazione_x0020_EN" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Codice_x0020_MIN" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Codice_x0020_AT" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Codice_x0020_UNSD_M49" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Codice_x0020_ISO_x0020_3166_x0020_alpha2" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Codice_x0020_ISO_x0020_3166_x0020_alpha3" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Codice_x0020_ISTAT_Stato_x0020_Padre" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Codice_x0020_ISO_x0020_alpha3_Stato_x0020_Padre" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== IleniaCentonze/terminology/input/vocabulary/statiEsteri/Territori_Figli.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Territori_Figli.xsd" generated="2020-02-27T17:55:33">
<Territori_Figli>
<Stato_x0028_S_x0029__x002F_Territorio_x0028_T_x0029_>T</Stato_x0028_S_x0029__x002F_Territorio_x0028_T_x0029_>
<Codice_x0020_Continente>5</Codice_x0020_Continente>
<Denominazione_x0020_Continente_x0020__x0028_IT_x0029_>Oceania</Denominazione_x0020_Continente_x0020__x0028_IT_x0029_>
<Codice_x0020_Area>50</Codice_x0020_Area>
<Denominazione_x0020_Area_x0020__x0028_IT_x0029_>Oceania</Denominazione_x0020_Area_x0020__x0028_IT_x0029_>
<code>902</code>
<display>Nuova Caledonia</display>
<Denominazione_x0020_EN>New Caledonia</Denominazione_x0020_EN>
<Codice_x0020_MIN>718</Codice_x0020_MIN>
<Codice_x0020_AT>Z716</Codice_x0020_AT>
<Codice_x0020_UNSD_M49>n.d.</Codice_x0020_UNSD_M49>
<Codice_x0020_ISO_x0020_3166_x0020_alpha2>NC</Codice_x0020_ISO_x0020_3166_x0020_alpha2>
<Codice_x0020_ISO_x0020_3166_x0020_alpha3>NCL</Codice_x0020_ISO_x0020_3166_x0020_alpha3>
<Codice_x0020_ISTAT_Stato_x0020_Padre>215</Codice_x0020_ISTAT_Stato_x0020_Padre>
<Codice_x0020_ISO_x0020_alpha3_Stato_x0020_Padre>FRA</Codice_x0020_ISO_x0020_alpha3_Stato_x0020_Padre>
</Territori_Figli>
<Territori_Figli>
<Stato_x0028_S_x0029__x002F_Territorio_x0028_T_x0029_>T</Stato_x0028_S_x0029__x002F_Territorio_x0028_T_x0029_>
<Codice_x0020_Continente>4</Codice_x0020_Continente>
<Denominazione_x0020_Continente_x0020__x0028_IT_x0029_>America</Denominazione_x0020_Continente_x0020__x0028_IT_x0029_>
<Codice_x0020_Area>42</Codice_x0020_Area>
<Denominazione_x0020_Area_x0020__x0028_IT_x0029_>America centro meridionale</Denominazione_x0020_Area_x0020__x0028_IT_x0029_>
<code>904</code>
<display>Saint-Martin (FR)</display>
<Denominazione_x0020_EN>Saint Martin (FR)</Denominazione_x0020_EN>
<Codice_x0020_MIN>542</Codice_x0020_MIN>
<Codice_x0020_AT>n.d.</Codice_x0020_AT>
<Codice_x0020_UNSD_M49>n.d.</Codice_x0020_UNSD_M49>
<Codice_x0020_ISO_x0020_3166_x0020_alpha2>MF</Codice_x0020_ISO_x0020_3166_x0020_alpha2>
<Codice_x0020_ISO_x0020_3166_x0020_alpha3>MAF</Codice_x0020_ISO_x0020_3166_x0020_alpha3>
<Codice_x0020_ISTAT_Stato_x0020_Padre>215</Codice_x0020_ISTAT_Stato_x0020_Padre>
<Codice_x0020_ISO_x0020_alpha3_Stato_x0020_Padre>FRA</Codice_x0020_ISO_x0020_alpha3_Stato_x0020_Padre>
</Territori_Figli>
<Territori_Figli>
<Stato_x0028_S_x0029__x002F_Territorio_x0028_T_x0029_>T</Stato_x0028_S_x0029__x002F_Territorio_x0028_T_x0029_>
<Codice_x0020_Continente>4</Codice_x0020_Continente>
<Denominazione_x0020_Continente_x0020__x0028_IT_x0029_>America</Denominazione_x0020_Continente_x0020__x0028_IT_x0029_>
<Codice_x0020_Area>42</Codice_x0020_Area>
<Denominazione_x0020_Area_x0020__x0028_IT_x0029_>America centro meridionale</Denominazione_x0020_Area_x0020__x0028_IT_x0029_>
<code>906</code>
<display>Saint-Barth√©lemy</display>
<Denominazione_x0020_EN>Saint Barthelemy</Denominazione_x0020_EN>
<Codice_x0020_MIN>541</Codice_x0020_MIN>
<Codice_x0020_AT>n.d.</Codice_x0020_AT>
<Codice_x0020_UNSD_M49>n.d.</Codice_x0020_UNSD_M49>
<Codice_x0020_ISO_x0020_3166_x0020_alpha2>BL</Codice_x0020_ISO_x0020_3166_x0020_alpha2>
<Codice_x0020_ISO_x0020_3166_x0020_alpha3>BLM</Codice_x0020_ISO_x0020_3166_x0020_alpha3>
<Codice_x0020_ISTAT_Stato_x0020_Padre>215</Codice_x0020_ISTAT_Stato_x0020_Padre>
<Codice_x0020_ISO_x0020_alpha3_Stato_x0020_Padre>FRA</Codice_x0020_ISO_x0020_alpha3_Stato_x0020_Padre>
</Territori_Figli>
<Territori_Figli>
<Stato_x0028_S_x0029__x002F_Territorio_x0028_T_x0029_>T</Stato_x0028_S_x0029__x002F_Territorio_x0028_T_x0029_>
<Codice_x0020_Continente>4</Codice_x0020_Continente>
<Denominazione_x0020_Continente_x0020__x0028_IT_x0029_>America</Denominazione_x0020_Continente_x0020__x0028_IT_x0029_>
<Codice_x0020_Area>41</Codice_x0020_Area>
<Denominazione_x0020_Area_x0020__x0028_IT_x0029_>America settentrionale</Denominazione_x0020_Area_x0020__x0028_IT_x0029_>
<code>908</code>
<display>Bermuda</display>
<Denominazione_x0020_EN>Bermuda</Denominazione_x0020_EN>
<Codice_x0020_MIN>508</Codice_x0020_MIN>
<Codice_x0020_AT>Z400</Codice_x0020_AT>
<Codice_x0020_UNSD_M49>n.d.</Codice_x0020_UNSD_M49>
<Codice_x0020_ISO_x0020_3166_x0020_alpha2>BM</Codice_x0020_ISO_x0020_3166_x0020_alpha2>
<Codice_x0020_ISO_x0020_3166_x0020_alpha3>BMU</Codice_x0020_ISO_x0020_3166_x0020_alpha3>
<Codice_x0020_ISTAT_Stato_x0020_Padre>219</Codice_x0020_ISTAT_Stato_x0020_Padre>
<Codice_x0020_ISO_x0020_alpha3_Stato_x0020_Padre>GBR</Codice_x0020_ISO_x0020_alpha3_Stato_x0020_Padre>
</Territori_Figli>
<Territori_Figli>
<Stato_x0028_S_x0029__x002F_Territorio_x0028_T_x0029_>T</Stato_x0028_S_x0029__x002F_Territorio_x0028_T_x0029_>
<Codice_x0020_Continente>5</Codice_x0020_Continente>
<Denominazione_x0020_Continente_x0020__x0028_IT_x0029_>Oceania</Denominazione_x0020_Continente_x0020__x0028_IT_x0029_>
<Codice_x0020_Area>50</Codice_x0020_Area>
<Denominazione_x0020_Area_x0020__x0028_IT_x0029_>Oceania</Denominazione_x0020_Area_x0020__x0028_IT_x0029_>
<code>909</code>
<display>Isole Cook (NZ)</display>
<Denominazione_x0020_EN>Cook Islands (NZ)</Denominazione_x0020_EN>
<Codice_x0020_MIN>702</Codice_x0020_MIN>
<Codice_x0020_AT>Z703</Codice_x0020_AT>
<Codice_x0020_UNSD_M49>n.d.</Codice_x0020_UNSD_M49>
<Codice_x0020_ISO_x0020_3166_x0020_alpha2>CK</Codice_x0020_ISO_x0020_3166_x0020_alpha2>
<Codice_x0020_ISO_x0020_3166_x0020_alpha3>COK</Codice_x0020_ISO_x0020_3166_x0020_alpha3>
<Codice_x0020_ISTAT_Stato_x0020_Padre>719</Codice_x0020_ISTAT_Stato_x0020_Padre>
<Codice_x0020_ISO_x0020_alpha3_Stato_x0020_Padre>NZL</Codice_x0020_ISO_x0020_alpha3_Stato_x0020_Padre>
</Territori_Figli>
<Territori_Figli>
<Stato_x0028_S_x0029__x002F_Territorio_x0028_T_x0029_>T</Stato_x0028_S_x0029__x002F_Territorio_x0028_T_x0029_>
<Codice_x0020_Continente>1</Codice_x0020_Continente>
<Denominazione_x0020_Continente_x0020__x0028_IT_x0029_>Europa</Denominazione_x0020_Continente_x0020__x0028_IT_x0029_>
<Codice_x0020_Area>13</Codice_x0020_Area>
<Denominazione_x0020_Area_x0020__x0028_IT_x0029_>Altri Paesi europei</Denominazione_x0020_Area_x0020__x0028_IT_x0029_>
<code>910</code>
<display>Gibilterra</display>
<Denominazione_x0020_EN>Gibraltar</Denominazione_x0020_EN>
<Codice_x0020_MIN>218</Codice_x0020_MIN>
<Codice_x0020_AT>Z113</Codice_x0020_AT>
<Codice_x0020_UNSD_M49>n.d.</Codice_x0020_UNSD_M49>
<Codice_x0020_ISO_x0020_3166_x0020_alpha2>GI</Codice_x0020_ISO_x0020_3166_x0020_alpha2>
<Codice_x0020_ISO_x0020_3166_x0020_alpha3>GIB</Codice_x0020_ISO_x0020_3166_x0020_alpha3>
<Codice_x0020_ISTAT_Stato_x0020_Padre>219</Codice_x0020_ISTAT_Stato_x0020_Padre>
<Codice_x0020_ISO_x0020_alpha3_Stato_x0020_Padre>GBR</Codice_x0020_ISO_x0020_alpha3_Stato_x0020_Padre>
</Territori_Figli>
<Territori_Figli>
<Stato_x0028_S_x0029__x002F_Territorio_x0028_T_x0029_>T</Stato_x0028_S_x0029__x002F_Territorio_x0028_T_x0029_>
<Codice_x0020_Continente>4</Codice_x0020_Continente>
<Denominazione_x0020_Continente_x0020__x0028_IT_x0029_>America</Denominazione_x0020_Continente_x0020__x0028_IT_x0029_>
<Codice_x0020_Area>42</Codice_x0020_Area>
<Denominazione_x0020_Area_x0020__x0028_IT_x0029_>America centro meridionale</Denominazione_x0020_Area_x0020__x0028_IT_x0029_>
<code>911</code>
<display>Isole Cayman</display>
<Denominazione_x0020_EN>Cayman Islands</Denominazione_x0020_EN>
<Codice_x0020_MIN>511</Codice_x0020_MIN>
<Codice_x0020_AT>Z530</Codice_x0020_AT>
<Codice_x0020_UNSD_M49>n.d.</Codice_x0020_UNSD_M49>
<Codice_x0020_ISO_x0020_3166_x0020_alpha2>KY</Codice_x0020_ISO_x0020_3166_x0020_alpha2>
<Codice_x0020_ISO_x0020_3166_x0020_alpha3>CYM</Codice_x0020_ISO_x0020_3166_x0020_alpha3>
<Codice_x0020_ISTAT_Stato_x0020_Padre>219</Codice_x0020_ISTAT_Stato_x0020_Padre>
<Codice_x0020_ISO_x0020_alpha3_Stato_x0020_Padre>GBR</Codice_x0020_ISO_x0020_alpha3_Stato_x0020_Padre>
</Territori_Figli>
<Territori_Figli>
<Stato_x0028_S_x0029__x002F_Territorio_x0028_T_x0029_>T</Stato_x0028_S_x0029__x002F_Territorio_x0028_T_x0029_>
<Codice_x0020_Continente>4</Codice_x0020_Continente>
<Denominazione_x0020_Continente_x0020__x0028_IT_x0029_>America</Denominazione_x0020_Continente_x0020__x0028_IT_x0029_>
<Codice_x0020_Area>42</Codice_x0020_Area>
<Denominazione_x0020_Area_x0020__x0028_IT_x0029_>America centro meridionale</Denominazione_x0020_Area_x0020__x0028_IT_x0029_>
<code>917</code>
<display>Anguilla</display>
<Denominazione_x0020_EN>Anguilla</Denominazione_x0020_EN>
<Codice_x0020_MIN>502</Codice_x0020_MIN>
<Codice_x0020_AT>Z529</Codice_x0020_AT>
<Codice_x0020_UNSD_M49>n.d.</Codice_x0020_UNSD_M49>
<Codice_x0020_ISO_x0020_3166_x0020_alpha2>AI</Codice_x0020_ISO_x0020_3166_x0020_alpha2>
<Codice_x0020_ISO_x0020_3166_x0020_alpha3>AIA</Codice_x0020_ISO_x0020_3166_x0020_alpha3>
<Codice_x0020_ISTAT_Stato_x0020_Padre>219</Codice_x0020_ISTAT_Stato_x0020_Padre>
<Codice_x0020_ISO_x0020_alpha3_Stato_x0020_Padre>GBR</Codice_x0020_ISO_x0020_alpha3_Stato_x0020_Padre>
</Territori_Figli>
<Territori_Figli>
<Stato_x0028_S_x0029__x002F_Territorio_x0028_T_x0029_>T</Stato_x0028_S_x0029__x002F_Territorio_x0028_T_x0029_>
<Codice_x0020_Continente>5</Codice_x0020_Continente>
<Denominazione_x0020_Continente_x0020__x0028_IT_x0029_>Oceania</Denominazione_x0020_Continente_x0020__x0028_IT_x0029_>
<Codice_x0020_Area>50</Codice_x0020_Area>
<Denominazione_x0020_Area_x0020__x0028_IT_x0029_>Oceania</Denominazione_x0020_Area_x0020__x0028_IT_x0029_>
<code>920</code>
<display>Polinesia francese</display>
<Denominazione_x0020_EN>French Polynesia</Denominazione_x0020_EN>
<Codice_x0020_MIN>724</Codice_x0020_MIN>
<Codice_x0020_AT>Z723</Codice_x0020_AT>
<Codice_x0020_UNSD_M49>n.d.</Codice_x0020_UNSD_M49>
<Codice_x0020_ISO_x0020_3166_x0020_alpha2>PF</Codice_x0020_ISO_x0020_3166_x0020_alpha2>
<Codice_x0020_ISO_x0020_3166_x0020_alpha3>PYF</Codice_x0020_ISO_x0020_3166_x0020_alpha3>
<Codice_x0020_ISTAT_Stato_x0020_Padre>215</Codice_x0020_ISTAT_Stato_x0020_Padre>
